spring:
  application-name: spring-boot-avro-kafka-producer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081
      specific:
        avro:
          reader: true

kafka:
  config:
    change:
      topic: config.change.topic
      group-id: scheduler.config.group